www/protected/modules/admin/controllers/AdminController.php
<?php

class AdminController extends BackendController
{
    /**
     * [filters description]
     * @return [type] [description]
     */
    public function filters()
    {
        return array('accessControl');
    }

    /**
     * [accessRules description]
     * @return [type] [description]
     */
    public function accessRules()
    {
        return array(
            array(
                'allow',
                'users'=>array('@'),
            ),
            array(
                'deny',
            )
        );
    }

    /**
     * [init description]
     * @return [type] [description]
     */
    public function init() {
        parent::init();
        $this->pageTitle = Yii::t('zh_CN', 'PAGE_TITLE_ADMIN');
    }

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id)
    {
        $this->render('view',array(
            'model'=>$this->loadModel($id),
        ));
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate()
    {
        $model=new Admin;
        if(isset($_POST['Admin']))
        {
            $model->attributes=$_POST['Admin'];
            if($model->validate()) {

                $model->password = CPasswordHelper::hashPassword($model->password);
                if ($model->save()) 
                    $this->redirect(array('view','id'=>$model->id));
            }
                
        }

        $this->render('create',array(
            'model'=>$model,
        ));
    }

    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id the ID of the model to be updated
     */
    public function actionUpdate($id)
    {
        $model=$this->loadModel($id);

        if(isset($_POST['Admin']))
        {
            $model->attributes=$_POST['Admin'];
            if($model->save())
                $this->redirect(array('view','id'=>$model->id));
        }

        $this->render('update',array(
            'model'=>$model,
        ));
    }

    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'admin' page.
     * @param integer $id the ID of the model to be deleted
     */
    public function actionDelete($id)
    {
        $criteria = new CDbCriteria;
        $criteria->order = 'id ASC';

        $admin = Admin::model()->find($criteria);
        if ($admin && $admin->id == $id) {
            throw new CHttpException(403, Yii::t('zh_CN', 'HTTP_STATUS_403_ADMIN_DEL'));
        }

        else {
            $this->loadModel($id)->delete();
            if(!isset($_GET['ajax']))
                $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));    
        }
        
    }

    /**
     * Lists all models.
     */
    public function actionIndex()
    {
        $dataProvider=new CActiveDataProvider('Admin');
        $this->render('index',array(
            'dataProvider'=>$dataProvider,
        ));
    }

    /**
     * Manages all models.
     */
    public function actionAdmin()
    {
        $model=new Admin('search');
        $model->unsetAttributes();  // clear any default values
        if(isset($_GET['Admin']))
            $model->attributes=$_GET['Admin'];

        $this->render('admin',array(
            'model'=>$model,
        ));
    }

    /**
     * Returns the data model based on the primary key given in the GET variable.
     * If the data model is not found, an HTTP exception will be raised.
     * @param integer $id the ID of the model to be loaded
     * @return Admin the loaded model
     * @throws CHttpException
     */
    public function loadModel($id)
    {
        $model=Admin::model()->findByPk($id);
        if($model===null)
            throw new CHttpException(404, Yii::t('zh_CN', 'HTTP_STATUS_404'));
        return $model;
    }

    /**
     * Performs the AJAX validation.
     * @param Admin $model the model to be validated
     */
    protected function performAjaxValidation($model)
    {
        if(isset($_POST['ajax']) && $_POST['ajax']==='admin-form')
        {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }
}

www/protected/modules/admin/views/admin/_form.php
<div class="well">
<?php $form=$this->beginWidget('CActiveForm', array(
    'id'=>'admin-form',
    'htmlOptions' => array(
        'class' => 'form-horizontal',
        'role' => 'form',
    ),
)); ?>

    <div class="form-group">
        <?php echo $form->labelEx($model,'email', array('class'=>"col-sm-2 control-label")); ?>
        <div class="col-sm-3">
        <?php echo $form->textField($model,'email',array('class'=>'form-control','maxlength'=>128)); ?>
        <?php echo $form->error($model,'email', array('class'=>'help-inline')); ?>
        </div>
    </div>

    <div class="form-group">
        <?php echo $form->labelEx($model,'password', array('class'=>"col-sm-2 control-label")); ?>
        <div class="col-sm-3">
        <?php echo $form->passwordField($model,'password',array('class'=>'form-control','maxlength'=>128, 'value'=>"")); ?>
        <?php echo $form->error($model,'password', array('class'=>'help-inline')); ?>
        </div>
    </div>

    <div class="form-group">
        <?php echo $form->labelEx($model,'status', array('class'=>"col-sm-2 control-label")); ?>
        <div class="col-sm-3">
        <?php echo $form->dropDownList($model,'status', $model->statusList(), array('class'=>'form-control')); ?>
        <?php echo $form->error($model,'status', array('class'=>'help-inline')); ?>
        </div>
    </div>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-3">
            <?php echo CHtml::submitButton($model->isNewRecord ? '添加' : '修改', array('class'=>'btn btn-primary')); ?>
            <a class="btn btn-default" href="<?php echo $this->createUrl("admin"); ?>">返回列表</a>
        </div>
    </div>

<?php $this->endWidget(); ?>
</div>

www/protected/modules/admin/views/admin/admin.php
<?php
$dataProvider = $model->search();
$data = $dataProvider->getData();
$page = $dataProvider->getPagination();
?>
<div class="row">
    <div class="col-md-12">
        <div class="row">
            <ol class="breadcrumb">
                <li><a href="<?php echo $this->createUrl("default/index"); ?>">Dashboard</a></li>
                <li><a href="<?php echo $this->createUrl("admin"); ?>">管理员管理</a></li>
                <li class="active">管理员列表</li>
                <li class="pull-right">
                    <a class="btn btn-xs btn-primary" href="<?php echo $this->createUrl("create"); ?>">新建</a>
                </li>
            </ol>
        </div>
        <div class="row">
          <?php $form = $this->beginWidget("CActiveForm", array(
                'id' => 'search-form',
                'htmlOptions' => array(
                    'class' => 'form-inline well',
                ),
                'method' => 'GET',
                'action' => $this->createUrl("admin"),
            )); ?>
            <div class="row">
            <div class="col-xs-2">
                <?php echo $form->textField($model, 'id', array('class'=>'form-control', 'placeholder'=>'id')); ?>
            </div>
            <div class="col-xs-2">
                <?php echo $form->textField($model, 'email', array('class'=>'form-control', 'placeholder'=>'邮箱')); ?>
            </div>
            <input type="submit" class="btn btn-primary" value="搜索">
            </div>
            <?php $this->endWidget(); ?>
            </div>
        <div class="row">
            <table class="table table-bordered table-condensed">
            <tr>
                <th style="width: 80px;"><?php echo $model->getAttributeLabel("id"); ?></th>
                <th><?php echo $model->getAttributeLabel("email"); ?></th>
                <th style="width: 60px;"><?php echo $model->getAttributeLabel("status"); ?></th>
                <th style="width: 160px;"><?php echo $model->getAttributeLabel("loginIp"); ?></th>
                <th style="width: 80px;"><?php echo $model->getAttributeLabel("createTime"); ?></th>
                <th style="width: 80px;"><?php echo $model->getAttributeLabel("updateTime"); ?></th>
                <th style="width: 120px;"></th>
            </tr>
            <?php  if ($data): ?>
            <?php  foreach ($data as $v): ?>
            <tr>
                <td><?php echo CHtml::encode($v->id); ?></td>
                <td><?php echo CHtml::encode($v->email); ?></td>
                <td><?php echo CHtml::encode($v->displayStatus()); ?></td>
                <td><?php echo CHtml::encode($v->loginIp); ?></td>
                <td><?php echo CHtml::encode($v->createTime?Util::timeElapsedStr($v->createTime):"-"); ?></td>
                <td><?php echo CHtml::encode($v->updateTime?Util::timeElapsedStr($v->updateTime):"-"); ?></td>
                <td style="text-align: center;">
                    <div class="btn-group">
                        <a class="btn btn-xs btn-danger" href="<?php echo $this->createUrl("admin/view", array("id"=>$v->id)); ?>">查看</a>
                        <a class="btn btn-xs btn-danger" href="<?php echo $this->createUrl("admin/delete", array("id"=>$v->id)) ?>">删除</a>
                        <a class="btn btn-xs btn-danger" href="<?php echo $this->createUrl("admin/update", array("id"=>$v->id)) ?>">编辑</a>
                    </div>
                </td>
            </tr>
            <?php endforeach; ?>
            <?php else: ?>
            <tr>
                <td colspan="99" style="text-align: center;">暂时没有数据。</td>
            </tr>
            <?php endif; ?>
            </table>
        </div>
        <div class="row">
            <?php $this->widget('CLinkPager', Util::page($page)); ?>
        </div>
    </div>
</div>

www/protected/modules/admin/views/admin/create.php
<div class="row">
    <div class="col-md-12">
        <div class="row">
            <ol class="breadcrumb">
                <li><a href="<?php echo $this->createUrl("default/index"); ?>">Dashboard</a></li>
                <li><a href="<?php echo $this->createUrl("admin"); ?>">管理员管理</a></li>
                <li class="active">新建管理员</li>
                <li class="pull-right">
                    <a class="btn btn-xs btn-primary" href="<?php echo $this->createUrl("admin"); ?>">返回列表</a>
                </li>
            </ol>
        </div>
        <div class="row">
        <?php $this->renderPartial('_form', array('model'=>$model)); ?>        </div>
    </div>
</div>

www/protected/modules/admin/views/admin/update.php
<div class="row">
    <div class="col-md-12">
        <div class="row">
            <ol class="breadcrumb">
                <li><a href="<?php echo $this->createUrl("default/index"); ?>">Dashboard</a></li>
                <li><a href="<?php echo $this->createUrl("admin"); ?>">管理员管理</a></li>
                <li class="active">修改员列表</li>
                <li class="pull-right">
                    <a class="btn btn-xs btn-primary" href="<?php echo $this->createUrl("admin"); ?>">返回列表</a>
                </li>
            </ol>
        </div>
        <div class="row">
        <?php $this->renderPartial('_form', array('model'=>$model)); ?>        </div>
    </div>
</div>

www/protected/modules/admin/views/admin/view.php
<div class="row">
    <div class="col-md-12">
        <div class="row">
            <ol class="breadcrumb">
                <li><a href="<?php echo $this->createUrl("default/index"); ?>">Dashboard</a></li>
                <li><a href="<?php echo $this->createUrl("admin"); ?>">管理员管理</a></li>
                <li class="active">浏览管理员</li>
                <li class="pull-right">
                    <a class="btn btn-xs btn-primary" href="<?php echo $this->createUrl("admin"); ?>">返回列表</a>
                </li>
            </ol>
        </div>
        <div class="row">
            <table class="table table-bordered table-condensed">
            <tr>
                <th style="width: 120px;"><?php echo $model->getAttributeLabel("id"); ?></th>
                <td><?php echo CHtml::encode($model->id); ?></td>
            </tr>
            <tr>
                <th><?php echo $model->getAttributeLabel("email"); ?></th>
                <td><?php echo CHtml::encode($model->email); ?></td>
            </tr>
            <tr>
                <th><?php echo $model->getAttributeLabel("status"); ?></th>
                <td><?php echo CHtml::encode($model->displayStatus()); ?></td>
            </tr>
            <tr>
                <th><?php echo $model->getAttributeLabel("loginIp"); ?></th>
                <td><?php echo CHtml::encode($model->loginIp); ?></td>
            </tr>
            <tr>
                <th><?php echo $model->getAttributeLabel("createTime"); ?></th>
                <td><?php echo CHtml::encode($model->createTime?Util::timeElapsedStr($model->createTime):"-"); ?></td>
            </tr>
            <tr>
                <th><?php echo $model->getAttributeLabel("updateTime"); ?></th>
                <td><?php echo CHtml::encode($model->updateTime?Util::timeElapsedStr($model->updateTime):"-"); ?></td>
            </tr>
                        </table>
        </div>
        <div class="row">
            <a class="btn btn-primary" href="<?php echo $this->createUrl("admin"); ?>">返回列表</a>
        </div>
    </div>
</div>