www/protected/modules/admin/controllers/NodeController.php
<?php

class NodeController extends BackendController
{

    public function init()
    {
        parent::init();
        $this->pageTitle = Yii::t('zh_CN', 'PAGE_TITLE_NODE');
    }

    /**
     * [filters description]
     * @return [type] [description]
     */
    public function filters()
    {
        return array('accessControl');
    }

    /**
     * [accessRules description]
     * @return [type] [description]
     */
    public function accessRules()
    {
        return array(
            array(
                'allow',
                'users'=>array('@'),
            ),
            array(
                'deny',
            )
        );
    }

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id)
    {
        $this->render('view',array(
            'model'=>$this->loadModel($id),
        ));
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate()
    {
        $model=new Node;

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if(isset($_POST['Node']))
        {
            $model->attributes=$_POST['Node'];
            if($model->save())
                $this->redirect(array('view','id'=>$model->id));
        }

        $this->render('create',array(
            'model'=>$model,
        ));
    }

    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id the ID of the model to be updated
     */
    public function actionUpdate($id)
    {
        $model=$this->loadModel($id);

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if(isset($_POST['Node']))
        {
            $model->attributes=$_POST['Node'];
            if($model->save())
                $this->redirect(array('view','id'=>$model->id));
        }

        $this->render('update',array(
            'model'=>$model,
        ));
    }

    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'admin' page.
     * @param integer $id the ID of the model to be deleted
     */
    public function actionDelete($id)
    {
        $this->loadModel($id)->delete();

        // if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
        if(!isset($_GET['ajax']))
            $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
    }

    /**
     * Lists all models.
     */
    public function actionIndex()
    {
        $dataProvider=new CActiveDataProvider('Node');
        $this->render('index',array(
            'dataProvider'=>$dataProvider,
        ));
    }

    /**
     * Manages all models.
     */
    public function actionAdmin()
    {
        $model=new Node('search');
        $model->unsetAttributes();  // clear any default values
        if(isset($_GET['Node']))
            $model->attributes=$_GET['Node'];

        $this->render('admin',array(
            'model'=>$model,
        ));
    }

    /**
     * Returns the data model based on the primary key given in the GET variable.
     * If the data model is not found, an HTTP exception will be raised.
     * @param integer $id the ID of the model to be loaded
     * @return Node the loaded model
     * @throws CHttpException
     */
    public function loadModel($id)
    {
        $model=Node::model()->findByPk($id);
        if($model===null)
            throw new CHttpException(404, Yii::t('zh_CN', 'HTTP_STATUS_404'));
        return $model;
    }

    /**
     * Performs the AJAX validation.
     * @param Node $model the model to be validated
     */
    protected function performAjaxValidation($model)
    {
        if(isset($_POST['ajax']) && $_POST['ajax']==='node-form')
        {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }
}

www/protected/modules/admin/views/node/_form.php
<div class="well">
<?php $form=$this->beginWidget('CActiveForm', array(
    'id'=>'node-form',
    'htmlOptions' => array(
        'class' => 'form-horizontal',
        'role' => 'form',
    ),
)); ?>

    <div class="form-group">
        <?php echo $form->labelEx($model,'name', array('class'=>"col-sm-2 control-label")); ?>
        <div class="col-sm-3">
        <?php echo $form->textField($model,'name',array('class'=>"form-control",'maxlength'=>64)); ?>
        <?php echo $form->error($model,'name', array('class'=>'help-inline')); ?>
        </div>
    </div>

    <div class="form-group">
        <?php echo $form->labelEx($model,'status', array('class'=>"col-sm-2 control-label")); ?>
        <div class="col-sm-3">
        <?php echo $form->dropDownList($model,'status', $model->statusList(), array('class'=>'form-control')); ?>
        <?php echo $form->error($model,'status', array('class'=>'help-inline')); ?>
        </div>
    </div>

    <div class="form-group">
        <?php echo $form->labelEx($model,'sort', array('class'=>"col-sm-2 control-label")); ?>
        <div class="col-sm-3">
        <?php echo $form->textField($model,'sort',array('class'=>'form-control','maxlength'=>10)); ?>
        <?php echo $form->error($model,'sort', array('class'=>'help-inline')); ?>
        </div>
    </div>

    <div class="form-group">
        <?php echo $form->labelEx($model,'description', array('class'=>"col-sm-2 control-label")); ?>
        <div class="col-sm-3">
        <?php echo $form->textArea($model,'description',array('class'=>'form-control','maxlength'=>256, 'style'=>'width:400px;height:60px;resize:none;')); ?>
        <?php echo $form->error($model,'description', array('class'=>'help-inline')); ?>
        </div>
    </div>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-3">
            <?php echo CHtml::submitButton($model->isNewRecord ? '添加' : '修改', array('class'=>'btn btn-primary')); ?>
            <a class="btn btn-default" href="<?php echo $this->createUrl("admin"); ?>">返回列表</a>
        </div>
    </div>

<?php $this->endWidget(); ?>
</div>

www/protected/modules/admin/views/node/admin.php
<?php
$dataProvider = $model->search();
$data = $dataProvider->getData();
$page = $dataProvider->getPagination();
?>
<div class="row">
    <div class="col-md-12">
        <div class="row">
            <ol class="breadcrumb">
                <li><a href="<?php echo $this->createUrl("default/index"); ?>">Dashboard</a></li>
                <li><a href="<?php echo $this->createUrl("admin") ?>">节点管理</a></li>
                <li class="active">节点列表</li>
                <li class="pull-right">
                    <a class="btn btn-xs btn-primary" href="<?php echo $this->createUrl("create"); ?>">新建</a>
                </li>
            </ol>
        </div>
        <div class="row">
        <?php $form = $this->beginWidget("CActiveForm", array(
                'id' => 'search-form',
                'htmlOptions' => array(
                    'class' => 'form-inline well',
                ),
                'method' => 'GET',
                'action' => $this->createUrl("admin"),
            )); ?>
            <div class="row">
            <div class="col-xs-2">
                <?php echo $form->textField($model, 'id', array('class'=>'form-control', 'placeholder'=>'id')); ?>
            </div>
            <div class="col-xs-2">
                <?php echo $form->textField($model, 'name',array('class'=>'form-control', 'placeholder'=>'名称')); ?>
            </div>
            <input type="submit" class="btn btn-primary" value="搜索">
            </div>
        <?php $this->endWidget(); ?>
        </div>
        <div class="row">
            <table class="table table-bordered table-condensed">
            <tr>
                <th style="width:80px;"><?php echo $model->getAttributeLabel("id"); ?></th>
                <th><?php echo $model->getAttributeLabel("name"); ?></th>
                <th style="width:80px;"><?php echo $model->getAttributeLabel("status"); ?></th>
                <th style="width:120px;"><?php echo $model->getAttributeLabel("sort"); ?></th>
                <th style="width:120px;"><?php echo $model->getAttributeLabel("createTime"); ?></th>
                <th style="width:120px;"></th>
            </tr>
            <?php  if ($data): ?>
            <?php  foreach ($data as $v): ?>
            <tr>
                <td><?php echo CHtml::encode($v->id); ?></td>
                <td><?php echo CHtml::encode($v->name); ?></td>
                <td><?php echo CHtml::encode($v->displayStatus()); ?></td>
                <td><?php echo CHtml::encode($v->sort); ?></td>
                <td><?php echo CHtml::encode($v->createTime?Util::timeElapsedStr($v->createTime):"-"); ?></td>
                <td style="text-align: center;">
                    <div class="btn-group">
                        <a class="btn btn-xs btn-danger" href="<?php echo $this->createUrl("node/view", array("id"=>$v->id)); ?>">查看</a>
                        <a class="btn btn-xs btn-danger" href="<?php echo $this->createUrl("node/delete", array("id"=>$v->id)) ?>">删除</a>
                        <a class="btn btn-xs btn-danger" href="<?php echo $this->createUrl("node/update", array("id"=>$v->id)) ?>">编辑</a>
                    </div>
                </td>
            </tr>
            <?php endforeach; ?>
            <?php else: ?>
            <tr>
                <td colspan="99" style="text-align: center;">暂时没有数据。</td>
            </tr>
            <?php endif; ?>
            </table>
        </div>
        <div class="row">
            <?php $this->widget('CLinkPager', Util::page($page)); ?>
        </div>
    </div>
</div>

www/protected/modules/admin/views/node/create.php
<div class="row">
    <div class="col-md-12">
        <div class="row">
            <ol class="breadcrumb">
                <li><a href="<?php echo $this->createUrl("default/index"); ?>">Dashboard</a></li>
                <li><a href="<?php echo $this->createUrl("admin") ?>">节点管理</a></li>
                <li class="active">新建节点</li>
                <li class="pull-right">
                    <a class="btn btn-xs btn-primary" href="<?php echo $this->createUrl("admin"); ?>">返回列表</a>
                </li>
            </ol>
        </div>
        <div class="row">
        <?php $this->renderPartial('_form', array('model'=>$model)); ?></div>
    </div>
</div>

www/protected/modules/admin/views/node/update.php
<div class="row">
    <div class="col-md-12">
        <div class="row">
            <ol class="breadcrumb">
                <li><a href="<?php echo $this->createUrl("default/index"); ?>">Dashboard</a></li>
                <li><a href="<?php echo $this->createUrl("admin") ?>">节点管理</a></li>
                <li class="active">修改节点</li>
                <li class="pull-right">
                    <a class="btn btn-xs btn-primary" href="<?php echo $this->createUrl("admin"); ?>">返回列表</a>
                </li>
            </ol>
        </div>
        <div class="row">
        <?php $this->renderPartial('_form', array('model'=>$model)); ?>        </div>
    </div>
</div>

www/protected/modules/admin/views/node/view.php
<div class="row">
    <div class="col-md-12">
        <div class="row">
            <ol class="breadcrumb">
                <li><a href="<?php echo $this->createUrl("default/index"); ?>">Dashboard</a></li>
                <li><a href="<?php echo $this->createUrl("admin") ?>">节点管理</a></li>
                <li class="active">浏览节点</li>
                <li class="pull-right">
                    <a class="btn btn-xs btn-primary" href="<?php echo $this->createUrl("admin"); ?>">返回列表</a>
                </li>
            </ol>
        </div>
        <div class="row">
            <table class="table table-bordered table-condensed">
            <tr>
                <th style="width:120px;"><?php echo $model->getAttributeLabel("id"); ?></th>
                <td><?php echo CHtml::encode($model->id); ?></td>
            </tr>
            <tr>
                <th><?php echo $model->getAttributeLabel("name"); ?></th>
                <td><?php echo CHtml::encode($model->name); ?></td>
            </tr>
            <tr>
                <th><?php echo $model->getAttributeLabel("status"); ?></th>
                <td><?php echo CHtml::encode($model->displayStatus()); ?></td>
            </tr>
            <tr>
                <th><?php echo $model->getAttributeLabel("sort"); ?></th>
                <td><?php echo CHtml::encode($model->sort); ?></td>
            </tr>
            <tr>
                <th><?php echo $model->getAttributeLabel("createTime"); ?></th>
                <td><?php echo CHtml::encode($model->createTime?Util::timeElapsedStr($model->createTime):"-"); ?></td>
            </tr>
            <tr>
                <th><?php echo $model->getAttributeLabel("description"); ?></th>
                <td><?php echo CHtml::encode($model->description); ?></td>
            </tr>
            </table>
        </div>
        <div class="row">
            <a class="btn btn-primary" href="<?php echo $this->createUrl("admin"); ?>">返回列表</a>
        </div>
    </div>
</div>